# Generated by Django 4.2.1 on 2023-05-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_session_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
    ]
